// <auto-generated />
namespace MySeenWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _46_add_bots_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_46_add_bots_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201710270734593_46_add_bots_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
