#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenMobileWebViewLib.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "AddFilm.cshtml"
using MySeenMobileWebViewLib;

#line default
#line hidden

#line 3 "AddFilm.cshtml"
using MySeenLib;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "3.11.0.0")]
public partial class AddFilm : PortableRazor.ViewBase
{

#line hidden

#line 4 "AddFilm.cshtml"
public FilmAddViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"jquery.mobile-1.4.0.min.css\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"jquery-1.10.2.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.mobile-1.4.0.min.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" src=\"bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <link");

WriteLiteral(" href=\"bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n</head>\r\n    <body>\r\n");


#line 21 "AddFilm.cshtml"
        

#line default
#line hidden

#line 21 "AddFilm.cshtml"
         if (!string.IsNullOrEmpty(Model.Name_Error))
        {

#line default
#line hidden
WriteLiteral(" <label");

WriteLiteral(" for=\"\"");

WriteLiteral(">");


#line 22 "AddFilm.cshtml"
                   Write(Model.Name_Error);


#line default
#line hidden
WriteLiteral("</label>");


#line 22 "AddFilm.cshtml"
                                                 }


#line default
#line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"editor-label\"");

WriteLiteral(">\r\n");


#line 24 "AddFilm.cshtml"
            

#line default
#line hidden

#line 24 "AddFilm.cshtml"
             if (Model.Unknown_Error)
            {

#line default
#line hidden
WriteLiteral(" <label");

WriteLiteral(" for=\"\"");

WriteLiteral(">UNKNOWN ERROR</label>");


#line 25 "AddFilm.cshtml"
                                                 }


#line default
#line hidden
WriteLiteral("        </div>\r\n\r\n\r\n\r\n");


#line 30 "AddFilm.cshtml"
        

#line default
#line hidden

#line 30 "AddFilm.cshtml"
         using (@Html.BeginForm("SaveFilm", "Home", new { name = @Model.Name }))
        {


#line default
#line hidden
WriteLiteral("            <h4>Name</h4>\r\n");


#line 33 "AddFilm.cshtml"
            

#line default
#line hidden

#line 33 "AddFilm.cshtml"
       Write(Html.TextArea("Name", Model.Name));


#line default
#line hidden

#line 33 "AddFilm.cshtml"
                                              


#line default
#line hidden
WriteLiteral("            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" />\r\n");


#line 35 "AddFilm.cshtml"
        }


#line default
#line hidden
WriteLiteral("        <div");

WriteLiteral(" data-role=\"footer\"");

WriteLiteral(" data-id=\"foo1\"");

WriteLiteral(" data-position=\"fixed\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" data-role=\"navbar\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "location.href=\'", true)

#line 38 "AddFilm.cshtml"
                                               , Tuple.Create<string,object,bool> ("", Url.Action("ShowFilmList")

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span>&nbsp;BAck</button>\r\n            </div>\r\n        </div>\r\n</body>\r\n</html>" +
"\r\n");

}
}
}
#pragma warning restore 1591
