#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenMobileWebViewLib.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "AddFilm.cshtml"
using MySeenMobileWebViewLib;

#line default
#line hidden

#line 3 "AddFilm.cshtml"
using MySeenLib;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "3.11.0.0")]
public partial class AddFilm : PortableRazor.ViewBase
{

#line hidden

#line 4 "AddFilm.cshtml"
public FilmAddViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" src=\"jquery-2.1.4.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery-2.1.4.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.mobile-1.4.5.min.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" src=\"jquery.lazyloadxt.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"bootstrap.min.js\"");

WriteLiteral("></script>\r\n\r\n    <link");

WriteLiteral(" href=\"jquery.mobile-1.4.5.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <link");

WriteLiteral(" href=\"bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n</head>\r\n    <body>\r\n        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n");


#line 25 "AddFilm.cshtml"
            

#line default
#line hidden

#line 25 "AddFilm.cshtml"
             if (Model.id == -1)
            { 


#line default
#line hidden
WriteLiteral("                <h4");

WriteLiteral(" class=\"modal-title text-center\"");

WriteLiteral(">Add Film</h4>\r\n");


#line 28 "AddFilm.cshtml"
            }
            else
            {


#line default
#line hidden
WriteLiteral("                <h4");

WriteLiteral(" class=\"modal-title text-center\"");

WriteLiteral(">Edit Film</h4>\r\n");


#line 32 "AddFilm.cshtml"
            }            


#line default
#line hidden
WriteLiteral("        </div>\r\n        <h3");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">");


#line 34 "AddFilm.cshtml"
                           Write(Model.Error);


#line default
#line hidden
WriteLiteral("</h3>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");


#line 36 "AddFilm.cshtml"
                

#line default
#line hidden

#line 36 "AddFilm.cshtml"
                 using (@Html.BeginForm("SaveFilm", "Home", new { Name = @Model.Name }, PortableRazor.Web.Mvc.HtmlHelper.FormMethod.Get, new { @class = "form-horizontal" }))
                {


#line default
#line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 39 "AddFilm.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Name, "Name", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");


#line 41 "AddFilm.cshtml"
                       Write(Html.TextBox("Name", @Model.Name, new { placeholder = @MySeenLib.Resource.Name, @class = "form-control movie-name" }));


#line default
#line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 45 "AddFilm.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Genre, "Genre", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" id=\"Genre\"");

WriteLiteral(" name=\"Genre\"");

WriteLiteral(" class=\"form-control movie-genre\"");

WriteLiteral(">\r\n");


#line 48 "AddFilm.cshtml"
                                

#line default
#line hidden

#line 48 "AddFilm.cshtml"
                                 foreach (var genre in @MySeenLib.Defaults.Genres.GetAll())
                                {


#line default
#line hidden
WriteLiteral("                                    <option ");


#line 50 "AddFilm.cshtml"
                                        Write(Model.Genre == MySeenLib.Defaults.Genres.GetId(genre) ? "selected" : "");


#line default
#line hidden
WriteLiteral(" value=\"");


#line 50 "AddFilm.cshtml"
                                                                                                                         Write(MySeenLib.Defaults.Genres.GetId(genre));


#line default
#line hidden
WriteLiteral("\">");


#line 50 "AddFilm.cshtml"
                                                                                                                                                                  Write(genre);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 51 "AddFilm.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </select>\r\n                        </div>\r\n          " +
"          </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 56 "AddFilm.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Rating, "Rating", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" id=\"Rating\"");

WriteLiteral(" name=\"Rating\"");

WriteLiteral(" class=\"form-control movie-rating\"");

WriteLiteral(">\r\n");


#line 59 "AddFilm.cshtml"
                                

#line default
#line hidden

#line 59 "AddFilm.cshtml"
                                 foreach (var rating in @MySeenLib.Defaults.Ratings.GetAll())
                                {


#line default
#line hidden
WriteLiteral("                                    <option ");


#line 61 "AddFilm.cshtml"
                                        Write(Model.Rating == MySeenLib.Defaults.Ratings.GetId(rating) ? "selected" : "");


#line default
#line hidden
WriteLiteral(" value=\"");


#line 61 "AddFilm.cshtml"
                                                                                                                            Write(MySeenLib.Defaults.Ratings.GetId(rating));


#line default
#line hidden
WriteLiteral("\">");


#line 61 "AddFilm.cshtml"
                                                                                                                                                                       Write(rating);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 62 "AddFilm.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </select>\r\n                        </div>\r\n          " +
"          </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary glyphicon glyphicon-arrow-left glyphicon-nonescaped\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "location.href=\'", true)

#line 67 "AddFilm.cshtml"
                                                                                                           , Tuple.Create<string,object,bool> ("", Url.Action("ShowFilmList")

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-arrow-left\"");

WriteLiteral("></span>&nbsp;Back</button>\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success glyphicon glyphicon-ok glyphicon-nonescaped\"");

WriteLiteral(" id=\"submitAddButton\"");

WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-ok\"");

WriteLiteral("></span>&nbsp;");


#line 68 "AddFilm.cshtml"
                                                                                                                                                                                    Write(Resource.Add);


#line default
#line hidden
WriteLiteral("</button>\r\n                    </div>\r\n");


#line 70 "AddFilm.cshtml"
                }


#line default
#line hidden
WriteLiteral("            </div>\r\n</body>\r\n</html>\r\n");

}
}
}
#pragma warning restore 1591
