#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenMobileWebViewLib.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "AddSerial.cshtml"
using MySeenMobileWebViewLib;

#line default
#line hidden

#line 3 "AddSerial.cshtml"
using MySeenLib;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "3.11.0.0")]
public partial class AddSerial : PortableRazor.ViewBase
{

#line hidden

#line 4 "AddSerial.cshtml"
public SerialAddViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"jquery.mobile-1.4.0.min.css\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"jquery-1.10.2.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.mobile-1.4.0.min.js\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" src=\"bootstrap.min.js\"");

WriteLiteral("></script>\r\n    <link");

WriteLiteral(" href=\"bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n</head>\r\n    <body>\r\n        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n            <h4");

WriteLiteral(" class=\"modal-title text-center\"");

WriteLiteral(">Add Serial</h4>\r\n        </div>\r\n        <h3");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">");


#line 23 "AddSerial.cshtml"
                           Write(Model.Error);


#line default
#line hidden
WriteLiteral("</h3>\r\n            <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");


#line 25 "AddSerial.cshtml"
                

#line default
#line hidden

#line 25 "AddSerial.cshtml"
                 using (@Html.BeginForm("SaveSerial", "Home", new { Name = @Model.Name, Season = @Model.Season, Series = @Model.Series }, PortableRazor.Web.Mvc.HtmlHelper.FormMethod.Get, new { @class = "form-horizontal" }))
                {


#line default
#line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 28 "AddSerial.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Name, "Name", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");


#line 30 "AddSerial.cshtml"
                       Write(Html.TextBox("Name", @Model.Name, new { placeholder = @MySeenLib.Resource.Name, @class = "form-control movie-name" }));


#line default
#line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 34 "AddSerial.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Season, "Season", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");


#line 36 "AddSerial.cshtml"
                       Write(Html.TextBox("Season", @Model.Season, new { placeholder = @MySeenLib.Resource.Season, @class = "form-control" }));


#line default
#line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 40 "AddSerial.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Series, "Series", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");


#line 42 "AddSerial.cshtml"
                       Write(Html.TextBox("Series", @Model.Series, new { placeholder = @MySeenLib.Resource.Series, @class = "form-control" }));


#line default
#line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 46 "AddSerial.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Genre, "Genre", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" id=\"Genre\"");

WriteLiteral(" name=\"Genre\"");

WriteLiteral(" class=\"form-control movie-genre\"");

WriteLiteral(">\r\n");


#line 49 "AddSerial.cshtml"
                                

#line default
#line hidden

#line 49 "AddSerial.cshtml"
                                 foreach (var genre in @MySeenLib.Defaults.Genres.GetAll())
                                {


#line default
#line hidden
WriteLiteral("                                    <option ");


#line 51 "AddSerial.cshtml"
                                        Write(Model.Genre == MySeenLib.Defaults.Genres.GetId(genre) ? "selected" : "");


#line default
#line hidden
WriteLiteral(" value=\"");


#line 51 "AddSerial.cshtml"
                                                                                                                         Write(MySeenLib.Defaults.Genres.GetId(genre));


#line default
#line hidden
WriteLiteral("\">");


#line 51 "AddSerial.cshtml"
                                                                                                                                                                  Write(genre);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 52 "AddSerial.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </select>\r\n                        </div>\r\n          " +
"          </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");


#line 57 "AddSerial.cshtml"
                   Write(Html.Label(@MySeenLib.Resource.Rating, "Rating", new { @class = "col-sm-2 control-label" }));


#line default
#line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-sm-10\"");

WriteLiteral(">\r\n                            <select");

WriteLiteral(" id=\"Rating\"");

WriteLiteral(" name=\"Rating\"");

WriteLiteral(" class=\"form-control movie-rating\"");

WriteLiteral(">\r\n");


#line 60 "AddSerial.cshtml"
                                

#line default
#line hidden

#line 60 "AddSerial.cshtml"
                                 foreach (var rating in @MySeenLib.Defaults.Ratings.GetAll())
                                {


#line default
#line hidden
WriteLiteral("                                    <option ");


#line 62 "AddSerial.cshtml"
                                        Write(Model.Rating == MySeenLib.Defaults.Ratings.GetId(rating) ? "selected" : "");


#line default
#line hidden
WriteLiteral(" value=\"");


#line 62 "AddSerial.cshtml"
                                                                                                                            Write(MySeenLib.Defaults.Ratings.GetId(rating));


#line default
#line hidden
WriteLiteral("\">");


#line 62 "AddSerial.cshtml"
                                                                                                                                                                       Write(rating);


#line default
#line hidden
WriteLiteral("</option>\r\n");


#line 63 "AddSerial.cshtml"
                                }


#line default
#line hidden
WriteLiteral("                            </select>\r\n                        </div>\r\n          " +
"          </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary glyphicon glyphicon-arrow-left glyphicon-nonescaped\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "location.href=\'", true)

#line 68 "AddSerial.cshtml"
                                                                                                           , Tuple.Create<string,object,bool> ("", Url.Action("ShowFilmList")

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral(">&nbsp;Back</button>\r\n                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success glyphicon glyphicon-ok glyphicon-nonescaped\"");

WriteLiteral(" id=\"submitAddButton\"");

WriteLiteral(">&nbsp;");


#line 69 "AddSerial.cshtml"
                                                                                                                                        Write(Resource.Add);


#line default
#line hidden
WriteLiteral("</button>\r\n                    </div>\r\n");


#line 71 "AddSerial.cshtml"
                }


#line default
#line hidden
WriteLiteral("            </div>\r\n</body>\r\n</html>\r\n");

}
}
}
#pragma warning restore 1591
