#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenMobileWebViewLib.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "Home.cshtml"
using MySeenMobileWebViewLib;

#line default
#line hidden

#line 3 "Home.cshtml"
using MySeenLib;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "3.11.0.0")]
public partial class Home : PortableRazor.ViewBase
{

#line hidden

#line 4 "Home.cshtml"
public HomeViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" src=\"jquery-1.10.2.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.mobile-1.4.0.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.lazyloadxt.js\"");

WriteLiteral("></script>\r\n\r\n    <link");

WriteLiteral(" href=\"bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"bootstrap.js\"");

WriteLiteral("></script>\r\n</head>\r\n    <body>\r\n        <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label>");


#line 22 "Home.cshtml"
                  Write(MySeenLib.Resource.SelectTheCategory);


#line default
#line hidden
WriteLiteral("</label>\r\n                <select");

WriteLiteral(" name=\"ComboBox\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" style=\"width : 100px\"");

WriteLiteral(">\r\n                    <option");

WriteLiteral(" value=\"1\"");

WriteLiteral(" ");


#line 24 "Home.cshtml"
                                  Write(Model.Selected == MySeenLib.Resource.Films ? " selected" : " ");


#line default
#line hidden
WriteLiteral(">");


#line 24 "Home.cshtml"
                                                                                                   Write(MySeenLib.Resource.Films);


#line default
#line hidden
WriteLiteral("</option>\r\n                    <option");

WriteLiteral(" value=\"2\"");

WriteLiteral(" ");


#line 25 "Home.cshtml"
                                  Write(Model.Selected == MySeenLib.Resource.Serials ? " selected" : " ");


#line default
#line hidden
WriteLiteral(">");


#line 25 "Home.cshtml"
                                                                                                     Write(MySeenLib.Resource.Serials);


#line default
#line hidden
WriteLiteral("</option>\r\n                </select>\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteAttribute ("onclick", " onclick=\"", "\""
, Tuple.Create<string,object,bool> ("", "location.href=\'", true)

#line 27 "Home.cshtml"
                                               , Tuple.Create<string,object,bool> ("", Url.Action("AddFilm")

#line default
#line hidden
, false)
, Tuple.Create<string,object,bool> ("", "\'", true)
);
WriteLiteral("><span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span>&nbsp;");


#line 27 "Home.cshtml"
                                                                                                                                                              Write(Resource.AddNew);


#line default
#line hidden
WriteLiteral("</button>\r\n                <label");

WriteLiteral(" for=\"quickSearch\"");

WriteLiteral(">");


#line 28 "Home.cshtml"
                                    Write(MySeenLib.Resource.QuickSearch);


#line default
#line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></span> :</label>\r\n            </div>\r\n        </div>\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(" id=\"table\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" width=\"60%\"");

WriteLiteral(">");


#line 34 "Home.cshtml"
                               Write(MySeenLib.Resource.Name);


#line default
#line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">");


#line 35 "Home.cshtml"
                               Write(MySeenLib.Resource.Date);


#line default
#line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">");


#line 36 "Home.cshtml"
                               Write(MySeenLib.Resource.Genre);


#line default
#line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">");


#line 37 "Home.cshtml"
                               Write(MySeenLib.Resource.Rating);


#line default
#line hidden
WriteLiteral("</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n");


#line 41 "Home.cshtml"
                

#line default
#line hidden

#line 41 "Home.cshtml"
                 foreach (var film in Model.FilmsList)
                {


#line default
#line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteLiteral(" class=\"align-left\"");

WriteLiteral(">");


#line 44 "Home.cshtml"
                                          Write(film.Name);


#line default
#line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"align-center\"");

WriteLiteral(">");


#line 45 "Home.cshtml"
                                            Write(film.DateSee10);


#line default
#line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"align-center\"");

WriteLiteral(">");


#line 46 "Home.cshtml"
                                            Write(film.GenreText);


#line default
#line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"align-center\"");

WriteLiteral(">");


#line 47 "Home.cshtml"
                                            Write(film.RatingText);


#line default
#line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");


#line 49 "Home.cshtml"
                }


#line default
#line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n</body>\r\n</html>\r\n");

}
}
}
#pragma warning restore 1591
