#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenAndroidLib.Views
{
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

#line 1 "Home.cshtml"
using MySeenAndroidLib;

#line default
#line hidden

#line 3 "Home.cshtml"
using MySeenLib;

#line default
#line hidden


[System.CodeDom.Compiler.GeneratedCodeAttribute("RazorTemplatePreprocessor", "3.11.0.0")]
public partial class Home : PortableRazor.ViewBase
{

#line hidden

#line 4 "Home.cshtml"
public HomeViewModel Model { get; set; }

#line default
#line hidden


public override void Execute()
{
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1\"");

WriteLiteral(" />\r\n\r\n    <script");

WriteLiteral(" src=\"jquery-1.10.2.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.mobile-1.4.0.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"jquery.lazyloadxt.js\"");

WriteLiteral("></script>\r\n\r\n\r\n    <link");

WriteLiteral(" href=\"bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n    <script");

WriteLiteral(" src=\"bootstrap.js\"");

WriteLiteral("></script>\r\n\r\n</head>\r\n    <body>\r\n        <div");

WriteLiteral(" class=\"form-inline\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                <label");

WriteLiteral(" for=\"lstSelected\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral(">");


#line 24 "Home.cshtml"
                                                            Write(MySeenLib.Resource.SelectTheCategory);


#line default
#line hidden
WriteLiteral("</label>\r\n\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" id=\"addButton\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></span>\r\n                    &nbsp;");


#line 28 "Home.cshtml"
                     Write(MySeenLib.Resource.AddNew);


#line default
#line hidden
WriteLiteral("\r\n                </button>\r\n                <label");

WriteLiteral(" for=\"quickSearch\"");

WriteLiteral(">");


#line 30 "Home.cshtml"
                                    Write(MySeenLib.Resource.QuickSearch);


#line default
#line hidden
WriteLiteral(" <span");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></span> :</label>\r\n            </div>\r\n        </div>\r\n        <table");

WriteLiteral(" class=\"table table-striped\"");

WriteLiteral(" id=\"table\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th");

WriteLiteral(" width=\"60%\"");

WriteLiteral(">");


#line 36 "Home.cshtml"
                               Write(MySeenLib.Resource.Name);


#line default
#line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" width=\"20%\"");

WriteLiteral(">");


#line 37 "Home.cshtml"
                               Write(MySeenLib.Resource.Date);


#line default
#line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">");


#line 38 "Home.cshtml"
                               Write(MySeenLib.Resource.Genre);


#line default
#line hidden
WriteLiteral("</th>\r\n                    <th");

WriteLiteral(" width=\"10%\"");

WriteLiteral(">");


#line 39 "Home.cshtml"
                               Write(MySeenLib.Resource.Rating);


#line default
#line hidden
WriteLiteral("</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n");


#line 43 "Home.cshtml"
                

#line default
#line hidden

#line 43 "Home.cshtml"
                 foreach (var film in Model.FilmsList)
                {


#line default
#line hidden
WriteLiteral("                    <tr>\r\n                        <td");

WriteLiteral(" class=\"align-left\"");

WriteLiteral(">");


#line 46 "Home.cshtml"
                                          Write(film.Name);


#line default
#line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"align-center\"");

WriteLiteral(">");


#line 47 "Home.cshtml"
                                            Write(film.DateSee10);


#line default
#line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"align-center\"");

WriteLiteral(">");


#line 48 "Home.cshtml"
                                            Write(film.GenreText);


#line default
#line hidden
WriteLiteral("</td>\r\n                        <td");

WriteLiteral(" class=\"align-center\"");

WriteLiteral(">");


#line 49 "Home.cshtml"
                                            Write(film.RatingText);


#line default
#line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");


#line 51 "Home.cshtml"
                }


#line default
#line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n</body>\r\n</html>\r\n");

}
}
}
#pragma warning restore 1591
