//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Seen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public Nullable<int> Id_R { get; set; }
        public int UsersId { get; set; }
        public string Name { get; set; }
        public string Authors { get; set; }
        public System.DateTime DateRead { get; set; }
        public int Genre { get; set; }
        public int Rating { get; set; }
        public System.DateTime DateChange { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
