//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Seen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serials
    {
        public long Id { get; set; }
        public int UsersId { get; set; }
        public string Name { get; set; }
        public int LastSeason { get; set; }
        public int LastSeries { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateLast { get; set; }
        public int Rate { get; set; }
        public System.DateTime DateChange { get; set; }
        public int Genre { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
