//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Seen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sync
    {
        public string Id { get; set; }
        public int UsersId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
