//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySeenLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Incorrect.
        /// </summary>
        public static string EmailIncorrect {
            get {
                return ResourceManager.GetString("EmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoon.
        /// </summary>
        public static string GenreCartoon {
            get {
                return ResourceManager.GetString("GenreCartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string GenreComedy {
            get {
                return ResourceManager.GetString("GenreComedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concert.
        /// </summary>
        public static string GenreConcert {
            get {
                return ResourceManager.GetString("GenreConcert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        public static string GenreDocumentary {
            get {
                return ResourceManager.GetString("GenreDocumentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string GenreDrama {
            get {
                return ResourceManager.GetString("GenreDrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastic.
        /// </summary>
        public static string GenreFantastic {
            get {
                return ResourceManager.GetString("GenreFantastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string GenreHorror {
            get {
                return ResourceManager.GetString("GenreHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        public static string GenreThriller {
            get {
                return ResourceManager.GetString("GenreThriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length &lt; 6.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password NOT Contains Digit.
        /// </summary>
        public static string PasswordNOTContainsDigit {
            get {
                return ResourceManager.GetString("PasswordNOTContainsDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and repeat not equal.
        /// </summary>
        public static string PasswordsNotEqual {
            get {
                return ResourceManager.GetString("PasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Short User Name.
        /// </summary>
        public static string ShortUserName {
            get {
                return ResourceManager.GetString("ShortUserName", resourceCulture);
            }
        }
    }
}
