//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySeenLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySeenLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Api Work Error.
        /// </summary>
        public static string ApiError {
            get {
                return ResourceManager.GetString("ApiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request Mode.
        /// </summary>
        public static string BadRequestMode {
            get {
                return ResourceManager.GetString("BadRequestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Begin.
        /// </summary>
        public static string DateBegin {
            get {
                return ResourceManager.GetString("DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Last.
        /// </summary>
        public static string DateLast {
            get {
                return ResourceManager.GetString("DateLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Clear.
        /// </summary>
        public static string DBDeleted {
            get {
                return ResourceManager.GetString("DBDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &amp; User data deleted.
        /// </summary>
        public static string DBUserDeleted {
            get {
                return ResourceManager.GetString("DBUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Incorrect.
        /// </summary>
        public static string EmailIncorrect {
            get {
                return ResourceManager.GetString("EmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter film name.
        /// </summary>
        public static string EnterFilmName {
            get {
                return ResourceManager.GetString("EnterFilmName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter season number.
        /// </summary>
        public static string EnterSeasonNumber {
            get {
                return ResourceManager.GetString("EnterSeasonNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter serial name.
        /// </summary>
        public static string EnterSerialName {
            get {
                return ResourceManager.GetString("EnterSerialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter serion number.
        /// </summary>
        public static string EnterSerionNumber {
            get {
                return ResourceManager.GetString("EnterSerionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Usename.
        /// </summary>
        public static string EnterUsename {
            get {
                return ResourceManager.GetString("EnterUsename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film name already exists.
        /// </summary>
        public static string FilmNameAlreadyExists {
            get {
                return ResourceManager.GetString("FilmNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Films.
        /// </summary>
        public static string Films {
            get {
                return ResourceManager.GetString("Films", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string Genre {
            get {
                return ResourceManager.GetString("Genre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartoon.
        /// </summary>
        public static string GenreCartoon {
            get {
                return ResourceManager.GetString("GenreCartoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comedy.
        /// </summary>
        public static string GenreComedy {
            get {
                return ResourceManager.GetString("GenreComedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concert.
        /// </summary>
        public static string GenreConcert {
            get {
                return ResourceManager.GetString("GenreConcert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documentary.
        /// </summary>
        public static string GenreDocumentary {
            get {
                return ResourceManager.GetString("GenreDocumentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drama.
        /// </summary>
        public static string GenreDrama {
            get {
                return ResourceManager.GetString("GenreDrama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fantastic.
        /// </summary>
        public static string GenreFantastic {
            get {
                return ResourceManager.GetString("GenreFantastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horror.
        /// </summary>
        public static string GenreHorror {
            get {
                return ResourceManager.GetString("GenreHorror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thriller.
        /// </summary>
        public static string GenreThriller {
            get {
                return ResourceManager.GetString("GenreThriller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Ep.
        /// </summary>
        public static string LastEpisode {
            get {
                return ResourceManager.GetString("LastEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length &lt; 6.
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password NOT Contains Digit.
        /// </summary>
        public static string PasswordNOTContainsDigit {
            get {
                return ResourceManager.GetString("PasswordNOTContainsDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and repeat not equal.
        /// </summary>
        public static string PasswordsNotEqual {
            get {
                return ResourceManager.GetString("PasswordsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial name already exists.
        /// </summary>
        public static string SerialNameAlreadyExists {
            get {
                return ResourceManager.GetString("SerialNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serials.
        /// </summary>
        public static string Serials {
            get {
                return ResourceManager.GetString("Serials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Short User Name.
        /// </summary>
        public static string ShortUserName {
            get {
                return ResourceManager.GetString("ShortUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync OK.
        /// </summary>
        public static string SyncOK {
            get {
                return ResourceManager.GetString("SyncOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Exist.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfull.
        /// </summary>
        public static string UserOK {
            get {
                return ResourceManager.GetString("UserOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
