#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MySeenAndroid.Resource", IsApplication=true)]

namespace MySeenAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int blue = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int green = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int red = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int ExitButton = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int MyButton = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int SelectorButton = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int f_datesee = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int f_genre = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int f_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int f_rate = 2131099651;
			
			// aapt resource value: 0x7f06000d
			public const int listView1 = 2131099661;
			
			// aapt resource value: 0x7f060008
			public const int tableRow1 = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int tableRowButtons = 2131099652;
			
			// aapt resource value: 0x7f06000b
			public const int table_datesee = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int table_genre = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int table_name = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int table_rate = 2131099660;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int column_row_films = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Test = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
