#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MySeenAndroid.Resource", IsApplication=true)]

namespace MySeenAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int blue = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int green = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int red = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060028
			public const int AddButton = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int ConfigButton = 2131099689;
			
			// aapt resource value: 0x7f06000d
			public const int Config_Sync = 2131099661;
			
			// aapt resource value: 0x7f06002a
			public const int ExitButton = 2131099690;
			
			// aapt resource value: 0x7f06000e
			public const int ExitButton_Config = 2131099662;
			
			// aapt resource value: 0x7f06001a
			public const int ExitButton_FilmAdd = 2131099674;
			
			// aapt resource value: 0x7f06003c
			public const int ExitButton_SerialAdd = 2131099708;
			
			// aapt resource value: 0x7f060019
			public const int SaveButton_FilmAd = 2131099673;
			
			// aapt resource value: 0x7f06003b
			public const int SaveButton_SerialAdd = 2131099707;
			
			// aapt resource value: 0x7f060014
			public const int config_error = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int config_info = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int content0 = 2131099671;
			
			// aapt resource value: 0x7f06000f
			public const int content1 = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int content_config_0 = 2131099659;
			
			// aapt resource value: 0x7f060039
			public const int content_s_0 = 2131099705;
			
			// aapt resource value: 0x7f06003d
			public const int content_s_1 = 2131099709;
			
			// aapt resource value: 0x7f06001f
			public const int e_film_genre = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int e_film_name = 2131099676;
			
			// aapt resource value: 0x7f060022
			public const int e_film_rate = 2131099682;
			
			// aapt resource value: 0x7f060012
			public const int edit_config_email = 2131099666;
			
			// aapt resource value: 0x7f06001d
			public const int edittext_film_name = 2131099677;
			
			// aapt resource value: 0x7f060043
			public const int edittext_season = 2131099715;
			
			// aapt resource value: 0x7f060040
			public const int edittext_serial_name = 2131099712;
			
			// aapt resource value: 0x7f060046
			public const int edittext_series = 2131099718;
			
			// aapt resource value: 0x7f060002
			public const int f_datesee = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int f_genre = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int f_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int f_rate = 2131099651;
			
			// aapt resource value: 0x7f060025
			public const int film_add_error = 2131099685;
			
			// aapt resource value: 0x7f060037
			public const int listView1 = 2131099703;
			
			// aapt resource value: 0x7f060008
			public const int s_datebegin = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int s_datelast = 2131099655;
			
			// aapt resource value: 0x7f060048
			public const int s_film_genre = 2131099720;
			
			// aapt resource value: 0x7f06003f
			public const int s_film_name = 2131099711;
			
			// aapt resource value: 0x7f06004b
			public const int s_film_rate = 2131099723;
			
			// aapt resource value: 0x7f060006
			public const int s_genre = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int s_name = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int s_rate = 2131099657;
			
			// aapt resource value: 0x7f060042
			public const int s_season = 2131099714;
			
			// aapt resource value: 0x7f060005
			public const int s_seasonseries = 2131099653;
			
			// aapt resource value: 0x7f060045
			public const int s_series = 2131099717;
			
			// aapt resource value: 0x7f060027
			public const int selectorSpinner = 2131099687;
			
			// aapt resource value: 0x7f06004e
			public const int serial_add_error = 2131099726;
			
			// aapt resource value: 0x7f06000a
			public const int spinnerItem = 2131099658;
			
			// aapt resource value: 0x7f060020
			public const int spinner_genre = 2131099680;
			
			// aapt resource value: 0x7f060049
			public const int spinner_genre_s = 2131099721;
			
			// aapt resource value: 0x7f060023
			public const int spinner_rate = 2131099683;
			
			// aapt resource value: 0x7f06004c
			public const int spinner_rate_s = 2131099724;
			
			// aapt resource value: 0x7f060033
			public const int stable_genre = 2131099699;
			
			// aapt resource value: 0x7f060026
			public const int tableRowButtons = 2131099686;
			
			// aapt resource value: 0x7f06000c
			public const int tableRowButtons_Config = 2131099660;
			
			// aapt resource value: 0x7f060018
			public const int tableRowButtons_FilmAdd = 2131099672;
			
			// aapt resource value: 0x7f06003a
			public const int tableRowButtons_SerialAdd = 2131099706;
			
			// aapt resource value: 0x7f06001b
			public const int tableRowTexts_FilmAdd_1 = 2131099675;
			
			// aapt resource value: 0x7f06001e
			public const int tableRowTexts_FilmAdd_2 = 2131099678;
			
			// aapt resource value: 0x7f060021
			public const int tableRowTexts_FilmAdd_3 = 2131099681;
			
			// aapt resource value: 0x7f060024
			public const int tableRowTexts_FilmAdd_4 = 2131099684;
			
			// aapt resource value: 0x7f06003e
			public const int tableRowTexts_SerialAdd_1 = 2131099710;
			
			// aapt resource value: 0x7f060047
			public const int tableRowTexts_SerialAdd_2 = 2131099719;
			
			// aapt resource value: 0x7f06004a
			public const int tableRowTexts_SerialAdd_3 = 2131099722;
			
			// aapt resource value: 0x7f06004d
			public const int tableRowTexts_SerialAdd_4 = 2131099725;
			
			// aapt resource value: 0x7f060041
			public const int tableRowTexts_SerialAdd_season = 2131099713;
			
			// aapt resource value: 0x7f060044
			public const int tableRowTexts_SerialAdd_series = 2131099716;
			
			// aapt resource value: 0x7f060010
			public const int tableRowTexts_config_1 = 2131099664;
			
			// aapt resource value: 0x7f060013
			public const int tableRowTexts_config_4 = 2131099667;
			
			// aapt resource value: 0x7f060015
			public const int tableRowTexts_config_5 = 2131099669;
			
			// aapt resource value: 0x7f06002b
			public const int tableRow_films = 2131099691;
			
			// aapt resource value: 0x7f060030
			public const int tableRow_serials = 2131099696;
			
			// aapt resource value: 0x7f060035
			public const int table_datebegin_s = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int table_datelast_s = 2131099700;
			
			// aapt resource value: 0x7f06002e
			public const int table_datesee_f = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int table_genre_f = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int table_name_f = 2131099692;
			
			// aapt resource value: 0x7f060031
			public const int table_name_s = 2131099697;
			
			// aapt resource value: 0x7f060036
			public const int table_rate = 2131099702;
			
			// aapt resource value: 0x7f06002f
			public const int table_rate_f = 2131099695;
			
			// aapt resource value: 0x7f060032
			public const int table_seasonseries_s = 2131099698;
			
			// aapt resource value: 0x7f060011
			public const int text_config_email = 2131099665;
			
			// aapt resource value: 0x7f060038
			public const int webView = 2131099704;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int column_row_films = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int column_row_serials = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int comboboxitem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Config = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FilmsAdd = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MainRazor = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SerialsAdd = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int AddNew = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int Config = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int DateBegin = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int DateLast = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int DateSee = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int Exit = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int Genre = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int LastSeries = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int Name = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int Rate = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int Test = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
